# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"append_file_ending": "00_core_solns.ipynb"}

modules = ["core.py"]

doc_url = "https://this_user.github.io/nbdev_playground/"

git_url = "https://github.com/this_user/nbdev_playground/tree/master/"

def custom_doc_links(name): return None
