# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core_solns.ipynb (unless otherwise specified).

__all__ = ['append_file_ending']

# Cell
#export
def append_file_ending(in_str):
    return in_str + '.csv'